spring:
  security:
    user:
      name: user
      password: password #  PasswordEncoder.encode(password)

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:3306/kip
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PASSWORD}
jwt:
  expiration: 3000 #30분 x 100 (50시간 임시로 설정) - 세종
  secretKey: ${JWT_SECRET}

fcm:
  certification : kip-fcm-firebase-adminsdk-gm80d-6a9b5bbd58.json

cloud:
  aws:
    s3:
      bucket: kip-s3
    credentials:
      access-key: ${ACCESS-KEY}
      secret-key: ${SECRET-KEY}
      username: ${S3_USERNAME}
      password: ${S3_PASSWORD}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
aws:
  os:
    region: ap-northeast-2
    endpoint: search-documents-dhcmbpyzm6u4x5mw3pug4tyoga.aos.ap-northeast-2.on.aws
    service-name : es