apiVersion: apps/v1
kind: Deployment
metadata:
  name: kip-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kip-backend
  template:
    metadata:
      labels:
        app: kip-backend
    spec:
      containers:
        - name: kip-backend
          image: 471112897563.dkr.ecr.ap-northeast-2.amazonaws.com/kip # ECR 주소
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: "500Mi"
            requests:
              cpu: "0.5"
              memory: "250Mi"
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-infos
                  key: DB_HOST
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-infos
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-infos
                  key: DB_PASSWORD
          volumeMounts:
            - name: fcm-secret-volume
              mountPath: "/etc/secrets"
              readOnly: true
      volumes:
        - name: fcm-secret-volume
          secret:
            secretName: fcm-secret

---
apiVersion: v1
kind: Service
metadata:
  name: kip-backend-service
spec:
# ClusterIP는 클러스터 내부에서만 접근가능한 Service를 생성
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: kip-backend