name: deploy KIP-Frontend

on:
  push:
    branches:
      - kip-frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # LTS 버전 사용

      - name: npm install
        working-directory: ./kip-fe
        run: npm install

      - name: npm generate
        working-directory: ./kip-fe
        run: npm run generate  # 정적 파일 생성

      - name: setup aws cli
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.S3_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          aws-region: "ap-northeast-2"

      - name: deploy to s3
        run: |
          aws s3 cp ./kip-fe/dist s3://kip-s3 --recursive  # dist 디렉터리 업로드
