name: deploy KIP-Frontend

on:
  push:
    branches:
    - kip-frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # LTS 버전 사용

      - name: set env
        run: |
          echo "VITE_BASE_URL=${{secrets.BASE_URL}}" >> .env
          echo "VUE_APP_FIREBASE_API_KEY=${{secrets.API_KEY}}" >> .env
          echo "VUE_APP_FIREBASE_AUTH_DOMAIN=${{secrets.DOMAIN}}" >> .env
          echo "VUE_APP_FIREBASE_PROJECT_ID=${{secrets.PROJECT_ID}}" >> .env
          echo "VUE_APP_FIREBASE_STORAGE_BUCKET=${{secrets.BUCKET}}" >> .env
          echo "VUE_APP_FIREBASE_MESSAGING_SENDER_ID=${{secrets.SENDER_ID}}" >> .env
          echo "VUE_APP_FIREBASE_APP_ID=${{secrets.APP_ID}}" >> .env
          echo "VUE_APP_FIREBASE_MEASUREMENTID=${{secrets.MEASUREMENT_ID}}" >> .env
          echo "VUE_APP_FIREBASE_VAP_ID=${{secrets.VAP_ID}}" >> .env

      - name: cat .env
        run: cat .env

      - name: Set JS
        run: |
          sudo mkdir -p /public
          sudo sh -c 'echo "${{ secrets.FIREBASE_JS }}" | base64 --decode > /public/firebase-messaging-sw.js && chmod 644 /public/firebase-messaging-sw.js'
          find /public

      - name: cat firebase
        run: cat /public/firebase-messaging-sw.js

      - name: npm install
        working-directory: ./kip-fe
        run: npm install

      - name: npm firebase install
        working-directory: ./kip-fe
        run: npm install firebase

      - name: npm generate
        working-directory: ./kip-fe
        run: npm run generate  # 정적 파일 생성

      - name: setup aws cli
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.S3_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          aws-region: "ap-northeast-2"

      - name: deploy to s3
        run: |
          aws s3 cp ./kip-fe/dist s3://kip-s3 --recursive  # dist 디렉터리 업로드
